<?php

function secret_phone_field_formatter_info() {
    $info = array(
        'secret_phone' => array(
            'label' => t('Secret Phone'),
            'field types' => array('text'),
            'description' => t('Replace some number with wildcard in a phone number')
        )
    );
    return $info;
}

function secret_phone_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

    $element = array();
    switch ($display['type']) {
        case 'secret_phone' :
            foreach($items as $delta => $item) {
                $element[$delta] = array(
                    '#theme' => 'secret_phone_mask',
                    '#data' => $item['value']
                );
            }
    }
    return $element;
}

function secret_phone_theme() {
    return array(
        'secret_phone_mask'  => array(
           'variables' => array(
               'data' => NULL
           )
        )
    );
}

function theme_secret_phone_mask($variables) {
    $phone = trim($variables['data']);
    // todo 添加数据判断, 如果为一个电话号码则进行操作
    if (strlen($phone) == 11) {
        return substr_replace($phone, "****", 3, -4);
    } else {
        // 当数据不是电话号码时,返回原数据
        return $variables['data'];
    }
}